### ISSUE TITLE
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?

### ISSUE THREAD

**Issue by xgocn** [weavedb/arnext#5]
```
PS D:\aos\arnext> yarn dev
yarn run v1.22.22
$ next dev
  ▲ Next.js 14.2.13
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 3.2s
 ○ Compiling / ...
 ✓ Compiled / in 8s (2101 modules)
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
    at path
    at svg
    at a
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at div
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at Flex2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/flex/flex.mjs:7:11)
    at Footer (webpack-internal:///./components/Footer.js:38:19)
    at div
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at div
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at Flex2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/flex/flex.mjs:7:11)
    at div
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at Home (webpack-internal:///./pages/index.js:58:17)
    at EnvironmentProvider (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/env/env.mjs:25:11)
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ThemeProvider (D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:145:32)
    at ThemeProvider (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/providers.mjs:10:11)
    at Provider (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/provider/provider.mjs:11:5)
    at ChakraProvider (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/provider/create-provider.mjs:8:5)
    at App (webpack-internal:///./pages/_app.js:18:16)
    at StyleRegistry (D:\aos\arnext\node_modules\styled-jsx\dist\index\index.js:449:36)
    at eU (D:\aos\arnext\node_modules\next\dist\compiled\next-server\pages.runtime.dev.js:8:20468)
    at eH (D:\aos\arnext\node_modules\next\dist\compiled\next-server\pages.runtime.dev.js:17:1788)
    at eJ (D:\aos\arnext\node_modules\next\dist\compiled\next-server\pages.runtime.dev.js:17:3091)
    at div
    at e9 (D:\aos\arnext\node_modules\next\dist\compiled\next-server\pages.runtime.dev.js:26:761)
Warning: Invalid DOM property `clip-rule`. Did you mean `clipRule`?
    at path
    at svg
    at a
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at div
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at Flex2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/flex/flex.mjs:7:11)
    at Footer (webpack-internal:///./components/Footer.js:38:19)
    at div
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at div
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at Flex2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/flex/flex.mjs:7:11)
    at div
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ChakraComponent2 (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/system.mjs:37:15)
    at Home (webpack-internal:///./pages/index.js:58:17)
    at EnvironmentProvider (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/env/env.mjs:25:11)
    at D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:89:25
    at ThemeProvider (D:\aos\arnext\node_modules\@emotion\react\dist\emotion-element-b1930563.cjs.js:145:32)
    at ThemeProvider (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/system/providers.mjs:10:11)
    at Provider (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/provider/provider.mjs:11:5)
    at ChakraProvider (file:///D:/aos/arnext/node_modules/@chakra-ui/react/dist/esm/provider/create-provider.mjs:8:5)
    at App (webpack-internal:///./pages/_app.js:18:16)
    at StyleRegistry (D:\aos\arnext\node_modules\styled-jsx\dist\index\index.js:449:36)
    at eU (D:\aos\arnext\node_modules\next\dist\compiled\next-server\pages.runtime.dev.js:8:20468)
    at eH (D:\aos\arnext\node_modules\next\dist\compiled\next-server\pages.runtime.dev.js:17:1788)
    at eJ (D:\aos\arnext\node_modules\next\dist\compiled\next-server\pages.runtime.dev.js:17:3091)
    at div
    at e9 (D:\aos\arnext\node_modules\next\dist\compiled\next-server\pages.runtime.dev.js:26:761)
 GET / 200 in 17201ms
 HEAD / 200 in 2149ms
 HEAD / 200 in 2961ms
 HEAD / 200 in 4458ms
 HEAD / 200 in 695ms
 HEAD / 200 in 694ms
 GET / 200 in 3996ms
 ○ Compiling /post/[id] ...
 ✓ Compiled /post/[id] in 807ms (2103 modules)
```

**Comment by tomoio** [comment]
I believe this warning comes from the UI library used for this particular app, but it's not related to the ArNext core. So I'm closing this. I will soon upload a simpler example without any UI/AO dependencies.
